# Generated by Django 4.2.2 on 2023-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('send', 'send'), ('rejected', 'rejected')], default='send', max_length=20),
        ),
    ]
