# Generated by Django 4.2.2 on 2023-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='send', max_length=20),
        ),
    ]
